// auth.js
// Single fixed product ("Educa") - no product selector in the UI anymore.
// Signup only needs a display name + password + phone; the email/username
// (identifier) is generated by the server, Gmail-style, and shown to the
// user once. Phone is stored encrypted (src/crypto.js), never plaintext,
// and is only ever used to verify a password-reset request matches the
// account it claims to be for.

const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const storage = require('./storage');
const cryptoBox = require('./crypto');
const { PRODUCT, DOMAIN } = require('./config');

const JWT_SECRET = process.env.JWT_SECRET;
if (!JWT_SECRET || JWT_SECRET.length < 32) {
  throw new Error(
    'JWT_SECRET missing or too short. Set a random 32+ char string in .env (e.g. `openssl rand -hex 32`).'
  );
}
const TOKEN_TTL = '30d';
const COOKIE_NAME = 'session';

function slugify(name) {
  const base = name.trim().toLowerCase().replace(/[^a-z0-9]/g, '');
  return base || 'user';
}

// Gmail-style duplicate handling: try the plain name first, then name2,
// name3, etc. until an identifier in this product namespace is free.
async function generateUniqueEmail(name) {
  const base = slugify(name);
  let candidate = `${base}@${DOMAIN}`;
  let suffix = 2;
  while (await storage.findUser(PRODUCT, candidate)) {
    candidate = `${base}${suffix}@${DOMAIN}`;
    suffix++;
    if (suffix > 9999) throw new Error('Could not generate a unique email, try a different name');
  }
  return candidate;
}

async function signup(name, password, phone) {
  if (!name || typeof name !== 'string' || name.trim().length < 2) {
    throw new Error('Name must be at least 2 characters');
  }
  if (!password || password.length < 6) throw new Error('Password must be at least 6 characters');

  const identifier = await generateUniqueEmail(name);
  const hash = await bcrypt.hash(password, 12);
  const encryptedPhone = phone ? cryptoBox.encrypt(phone) : '';
  await storage.createUser(PRODUCT, identifier, hash, encryptedPhone);
  return { product: PRODUCT, identifier };
}


// ⭐ DYNAMIC STORE DB FALLBACK FOR INSTANT SSO LOGIN
let storeDbConnection = null;
function getStoreDb() {
  const uri = process.env.STORE_MONGO_URI;
  if (!uri) return null;
  if (!storeDbConnection) {
    storeDbConnection = require('mongoose').createConnection(uri);
  }
  return storeDbConnection;
}

async function findStoreUserAndSync(identifier) {
  try {
    const storeConn = getStoreDb();
    if (!storeConn) return null;
    const normId = (identifier || '').trim().toLowerCase();
    const baseId = normId.split('@')[0];
    const StoreUser = storeConn.models.StoreUser || storeConn.model('StoreUser', new require('mongoose').Schema({}, { strict: false }), 'users');
    
    // Find user in store DB by email, name (DB001, etc.), or userId
    const u = await StoreUser.findOne({
      $or: [
        { email: normId },
        { email: `${baseId}@educa.com` },
        { email: `${baseId}@educaveda.com` },
        { name: { $regex: new RegExp(`^${normId}$`, 'i') } },
        { name: { $regex: new RegExp(`^${baseId}$`, 'i') } },
        { userId: { $regex: new RegExp(`^${normId}$`, 'i') } }
      ]
    }).lean();

    if (u) {
      // If user is blocked or deleted in Store, remove from Mailbox and throw
      if (u.isBlocked) {
        await storage.deleteUser(PRODUCT, normId).catch(() => {});
        if (u.email) await storage.deleteUser(PRODUCT, u.email).catch(() => {});
        throw new Error("Aapka account admin dwara block kiya gaya hai.");
      }
      if (u.isDeleted) {
        await storage.deleteUser(PRODUCT, normId).catch(() => {});
        if (u.email) await storage.deleteUser(PRODUCT, u.email).catch(() => {});
        throw new Error("Aapka account delete kiya ja chuka hai.");
      }

      if (u.password) {
        const storeHash = u.password;
        const targetEmail = (u.email || normId).trim().toLowerCase();
        const userName = (u.name || '').trim().toLowerCase();

        // All aliases for this user across Educa ecosystem
        const aliasList = [
          normId,
          targetEmail,
          userName,
          `${userName}@educaveda.com`,
          `${userName}@educa.com`,
          `${baseId}@educaveda.com`,
          `${baseId}@educa.com`
        ].filter(Boolean);

        const uniqueAliases = [...new Set(aliasList)];

        // Ensure every alias in mailbox database has the latest store password hash
        for (const alias of uniqueAliases) {
          const existing = await storage.findUser(PRODUCT, alias);
          if (existing) {
            if (existing.passwordHash !== storeHash) {
              await storage.updatePassword(PRODUCT, alias, storeHash);
            }
          } else {
            await storage.createUser(
              PRODUCT,
              alias,
              storeHash,
              u.phone || ''
            ).catch(() => {});
          }
        }

        return {
          product: PRODUCT,
          identifier: targetEmail || normId,
          passwordHash: storeHash,
          phone: u.phone || ''
        };
      }
    }
  } catch (e) {
    if (e.message && (e.message.includes('block') || e.message.includes('delete'))) {
      throw e;
    }
    console.error('Store DB fallback error:', e.message);
  }
  return null;
}


// ⭐ DYNAMIC UDAAN DB FALLBACK FOR INSTANT LOGIN
let udaanDbConnection = null;
function getUdaanDb() {
  const uri = process.env.UDAAN_MONGO_URI || 'mongodb+srv://muhammadaleemali888_db_user:k6DVmZ7sWT0EykzF@cluster0.nxu5izr.mongodb.net/udaan-achievers?retryWrites=true&w=majority';
  if (!udaanDbConnection) {
    udaanDbConnection = require('mongoose').createConnection(uri);
  }
  return udaanDbConnection;
}

async function findUdaanUserAndSync(identifier) {
  try {
    const conn = getUdaanDb();
    const normId = (identifier || '').trim().toLowerCase();
    const Student = conn.models.Student || conn.model('Student', new require('mongoose').Schema({}, { strict: false }), 'students');
    const u = await Student.findOne({
      $or: [
        { email: normId },
        { studentId: { $regex: new RegExp(`^${normId}$`, 'i') } }
      ]
    }).lean();

    if (u && u.passwordHash) {
      await storage.createUser(
        PRODUCT,
        normId,
        u.passwordHash,
        ''
      );
      return await storage.findUser(PRODUCT, normId);
    }
  } catch(e) {
    console.error('Udaan DB fallback error:', e.message);
  }
  return null;
}

async function login(identifier, password) {
  identifier = identifier.trim().toLowerCase();

  // First check Store DB status (to enforce real-time blocks / deletes & live password sync)
  let storeUser = null;
  try {
    storeUser = await findStoreUserAndSync(identifier);
  } catch (err) {
    if (err.message && (err.message.includes('block') || err.message.includes('delete'))) {
      throw err;
    }
  }

  let user = storeUser || (await storage.findUser(PRODUCT, identifier));
  if (!user) {
    user = await findUdaanUserAndSync(identifier);
  }
  if (!user) {
    await bcrypt.compare(password, '$2b$12$invalidsaltinvalidsaltinvalidsal.');
    throw new Error('Invalid email or password');
  }
  if (storage.isLocked(user)) {
    throw new Error('Account temporarily locked due to repeated failed attempts. Try again later.');
  }
  let ok = await bcrypt.compare(password, user.passwordHash);

  // If password comparison failed with primary hash, check if store DB has matching password
  if (!ok && storeUser && storeUser.passwordHash) {
    const storeOk = await bcrypt.compare(password, storeUser.passwordHash);
    if (storeOk) {
      await storage.updatePassword(PRODUCT, identifier, storeUser.passwordHash);
      ok = true;
    }
  }

  if (!ok) {
    await storage.recordFailedLogin(PRODUCT, identifier);
    throw new Error('Invalid email or password');
  }
  await storage.clearFailedLogins(PRODUCT, identifier);
  return { product: PRODUCT, identifier: user.identifier || identifier };
}

function resetPassword(identifier, newPassword) {
  return bcrypt.hash(newPassword, 12).then(hash => storage.updatePassword(PRODUCT, identifier, hash));
}

// Only creates a pending admin request if the submitted phone matches the
// (decrypted) phone stored on the account - this is the "gate" that stops
// someone from requesting a reset for an account that isn't theirs. Always
// looks and behaves the same either way to the caller (see api.js) so this
// can't be used to probe which identifiers/phones are valid.
async function checkAndCreateResetRequest(identifier, submittedPhone) {
  const user = await storage.findUser(PRODUCT, identifier.trim().toLowerCase());
  if (!user || !user.phone) return false;
  const storedPhone = cryptoBox.decrypt(user.phone);
  const normalize = (p) => String(p).replace(/[^0-9]/g, '');
  if (normalize(storedPhone) !== normalize(submittedPhone)) return false;
  await storage.createResetRequest(PRODUCT, identifier, storedPhone);
  return true;
}

function issueToken(product, identifier) {
  return jwt.sign({ product, identifier }, JWT_SECRET, { expiresIn: TOKEN_TTL });
}

function setSessionCookie(res, product, identifier) {
  const token = issueToken(product, identifier);
  const sameSite = process.env.COOKIE_SAME_SITE || 'lax';
  res.cookie(COOKIE_NAME, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production' || sameSite === 'none',
    sameSite,
    maxAge: 2 * 60 * 60 * 1000,
  });
}

function clearSessionCookie(res) {
  res.clearCookie(COOKIE_NAME);
}

function requireAuth(req, res, next) {
  const authHeader = req.headers.authorization;
  const bearerToken = authHeader && authHeader.startsWith('Bearer ') ? authHeader.slice(7) : null;
  const token = bearerToken || req.cookies?.[COOKIE_NAME];
  if (!token) return res.status(401).json({ error: 'Not authenticated' });
  try {
    const payload = jwt.verify(token, JWT_SECRET);
    req.user = { product: payload.product, identifier: payload.identifier };
    next();
  } catch (err) {
    return res.status(401).json({ error: 'Session invalid or expired' });
  }
}

module.exports = {
  signup, login, resetPassword, checkAndCreateResetRequest,
  setSessionCookie, clearSessionCookie, requireAuth, issueToken, COOKIE_NAME,
};
